version: "3.4"

services:
  app:
    build:
      context: .
      target: development
    command: sh -c "npm run up:dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - backend

  database:
    container_name: database
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - backend
#    volumes:
#      - ./pgdata:/var/lib/postgres/data

networks:
  backend:
    driver: bridge
